In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from optimiz.classifier import LinearClassifier
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
import torch
from optimiz.facility_location import FacilityLocation

In [2]:
from sklearn.datasets import make_classification
from sklearn.datasets import fetch_openml

from sklearn.datasets import make_classification

X, y = make_classification(n_samples=10000, n_features=20, n_classes=2, random_state=42)


In [3]:
print("Size of X :" , X.shape)
print("Size of y : " , y.shape)

Size of X : (10000, 20)
Size of y :  (10000,)


In [5]:
facilityLocation = FacilityLocation(X , y)
#print(facilityLocation.idx)
subset = facilityLocation.greedy_selection(subset_size=2000)
print(len(subset))

Calculating paiwise distance
Done calculating pairwise distance
Done calculating gain for 1000
Done calculating gain for 2000
Done calculating gain for 3000
Done calculating gain for 4000
Done calculating gain for 5000
Done calculating gain for 6000
Done calculating gain for 7000
Done calculating gain for 8000
Done calculating gain for 9000
Done calculating gain for 10000
Done calculating gain for 1000
Done calculating gain for 2000
Done calculating gain for 3000
Done calculating gain for 4000
Done calculating gain for 5000
Done calculating gain for 6000
Done calculating gain for 7000
Done calculating gain for 8000
Done calculating gain for 9000
Done calculating gain for 10000
Done calculating gain for 1000
Done calculating gain for 2000
Done calculating gain for 3000
Done calculating gain for 4000
Done calculating gain for 5000
Done calculating gain for 6000
Done calculating gain for 7000
Done calculating gain for 8000
Done calculating gain for 9000
Done calculating gain for 10000
Don

In [17]:
print(np.unique(y_train))

[0 1]


In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X[subset],y[subset],
                                                 test_size = 0.3,
                                                 random_state = 42)

clf = LinearClassifier(learning_rate=0.000001 ,tolerance=0.000001, iterations=1000 , optimizer_type="newton")
clf.fit(X_train , y_train , scale=True)


[0.20182494 0.20147382 0.72480967 ... 0.79402287 0.37315022 0.74911927]
Iteration : 1 , Loss : 512.5731609108518
[0.09521285 0.08139935 0.81188403 ... 0.87759205 0.25536553 0.86471883]
Iteration : 2 , Loss : 416.43841006447127
[0.05347775 0.03760439 0.85356384 ... 0.90818664 0.17481831 0.92584698]
Iteration : 3 , Loss : 390.28049946066574
[0.04000038 0.02484756 0.86832875 ... 0.9168418  0.13852452 0.94949786]
Iteration : 4 , Loss : 386.6314631808934
[0.03769234 0.02275762 0.87075402 ... 0.91808309 0.13125988 0.95383027]
Iteration : 5 , Loss : 386.521825503463
[0.03761299 0.02268534 0.87082908 ... 0.91811963 0.13099115 0.95398522]
Iteration : 6 , Loss : 386.52169477926475
[0.03761289 0.02268525 0.87082916 ... 0.91811967 0.13099081 0.95398541]
Iteration : 7 , Loss : 386.52169477906375
Converged after 7 iterations
[0.03761289 0.02268525 0.87082916 ... 0.91811967 0.13099081 0.95398541]
Iteration : 8 , Loss : 386.521694779064
Converged after 8 iterations
[0.03761289 0.02268525 0.87082916 ..

[np.float64(512.5731609108518),
 np.float64(416.43841006447127),
 np.float64(390.28049946066574),
 np.float64(386.6314631808934),
 np.float64(386.521825503463),
 np.float64(386.52169477926475),
 np.float64(386.52169477906375),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064),
 np.float64(386.521694779064)